CREATE EXTENSION IF NOT EXISTS vector;
CREATE ROLE journal_test LOGIN PASSWORD 'integration-test-only' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
GRANT CONNECT ON DATABASE test TO journal_test;
GRANT ALL ON SCHEMA public TO journal_test;
