import { useState } from 'react';
import { BookHeart, Crown, Download, LogOut, ShieldCheck } from 'lucide-react';
import { authProvider } from '../../auth/authProvider';
import { DeleteAccountDialog } from '../account/DeleteAccountDialog';
import { DataExportDialog } from '../account/DataExportDialog';

export function Header({ user, identity, setError }) {
  const [showDeletion, setShowDeletion] = useState(false);
  const [showExport, setShowExport] = useState(false);
  const admin = identity?.roles?.includes('ADMIN');
  return <><header className="sticky top-0 z-20 border-b border-white/70 bg-white/70 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-10"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 via-fuchsia-500 to-rose-400 text-white shadow-lg shadow-violet-200"><BookHeart className="h-6 w-6" /></div><div><h1 className="font-serif text-xl font-semibold tracking-tight text-slate-800 sm:text-2xl">Gemini Journal</h1><p className="hidden text-[10px] font-bold uppercase tracking-[.2em] text-violet-500 sm:block">Your colorful private space</p></div></div><div className="flex items-center gap-2 sm:gap-3">{admin ? <span className="hidden items-center gap-1 rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-700 sm:inline-flex"><Crown className="h-3.5 w-3.5" />Admin</span> : <span className="hidden rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700 sm:inline">Secure · User</span>}<div className="hidden items-center gap-2 md:flex">{user.photoURL ? <img className="h-9 w-9 rounded-full border-2 border-white shadow" src={user.photoURL} alt="Your profile" referrerPolicy="no-referrer" /> : <div className="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-indigo-100 to-rose-100 text-xs font-bold text-violet-700">{user.email?.[0]?.toUpperCase()}</div>}<span className="max-w-44 truncate text-sm text-slate-500">{user.email}</span></div><button type="button" onClick={() => setShowExport(true)} className="icon-button" aria-label="Download your data"><Download /></button><button type="button" onClick={() => setShowDeletion(true)} className="icon-button" aria-label="Privacy and account deletion"><ShieldCheck /></button><button onClick={() => authProvider.logout()} className="icon-button hover:!text-rose-500" aria-label="Sign out"><LogOut /></button></div></div></header>{showExport && <DataExportDialog onClose={() => setShowExport(false)} setError={setError} />}{showDeletion && <DeleteAccountDialog onClose={() => setShowDeletion(false)} />}</>;
}
