spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
app.gemini.api-key-secret=${GEMINI_API_KEY_SECRET}
app.google-cloud.project-id=${GOOGLE_CLOUD_PROJECT}
app.google-cloud.firestore-database-id=${FIRESTORE_DATABASE_ID}
